// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Areas.Admin.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2024, 5, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DisplayOrder = 1,
                            Name = "Keyboards"
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2024, 5, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DisplayOrder = 2,
                            Name = "Mouses"
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedDateTime = new DateTime(2024, 5, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DisplayOrder = 3,
                            Name = "Headphones"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Description = "",
                            ImgUrl = "",
                            Name = "Razer Headphones",
                            Price = 30m
                        },
                        new
                        {
                            ProductID = 2,
                            Description = "",
                            ImgUrl = "",
                            Name = "HyperX Mouse",
                            Price = 110m
                        },
                        new
                        {
                            ProductID = 3,
                            Description = "",
                            ImgUrl = "",
                            Name = "Razor Keyboard",
                            Price = 70m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
